#!/usr/bin/env bash

for src_file in $(git diff --cached --name-only --diff-filter=ACM | grep '\.src\.html$'); do
    output_file="${src_file/.src.html/.html}"

    minify --html "$src_file" > "$output_file"
    git add "$output_file"
done
