#!/usr/bin/env osascript -l JavaScript
// vim: ft=javascript

// SEE "JXA Cookbook"
// https://github.com/JXA-Cookbook/JXA-Cookbook/wiki

const E_MISSING_FILE = 16

const getEnv = key => $.getenv(key)
const homeDir = () => getEnv('HOME')
const fileExists = file => $.NSFileManager.defaultManager.fileExistsAtPath(file)
const log = (...args) => console.log(...args)

const errorBox = (app, msg) => {
	app.displayAlert(msg)
	log(msg)
}

const fatal = (app, code, msg) => {
	errorBox(app, msg)
	$.exit(code)
}

const requireFile = (app, file) => {
	if (fileExists(file)) return
	fatal(app, E_MISSING_FILE, `File does not exist at path: ${filePath}`)
}

const setAllDesktops = app => {
	log('Setting desktops')

	app.desktops().forEach(desktop => {
		const name = desktop.name()

		const filePaths = [
			`${homeDir()}/.config/wallpaper/images/${name}`,
			`${homeDir()}/.config/wallpaper/images/default`,
		]

		const file = filePaths.find(fileExists)

		if (!file) {
			log(`No image file found for ${name}`)
			return
		}

		const result = desktop.picture.set(file)

		log(`${name} ${result}`)
	})
}

function run(argv) {
	ObjC.import('stdlib')

	const app = Application('System Events')
	app.includeStandardAdditions = true

	setAllDesktops(app)

	$.exit(0)
}
