#!/usr/bin/env zsh

# @raycast.author Rémino Rem
# @raycast.authorURL https://remino.net
# @raycast.packageName 1Password
# @raycast.schemaVersion 1
# @raycast.title Restart 1Password
# @raycast.description Quit 1Password and restart it.
# @raycast.mode silent
# @raycast.icon 🔑

pgrep 1Password | xargs kill -s TERM
open -a 1Password
