#!/usr/bin/env zsh

# @raycast.author Rémino Rem
# @raycast.authorURL https://remino.net
# @raycast.packageName Projects
# @raycast.schemaVersion 1
# @raycast.title Create Project Folder
# @raycast.description Creates a dated project folder with mkprj.
# @raycast.mode silent
# @raycast.argument1 { "type": "text", "placeholder": "Project name" }
# @raycast.icon 📁

_mkprj() {
	local name="$1"

	if [[ "$name" == "~"* ]]; then
		name="${HOME}${name:1}"
	fi

	mkprj "$name"
}

_mkprj "$1" | while read -r name; do
	open "$name"
done
